import { inter } from "@/components/ui/fonts";
import "@/styles/globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="flex min-h-screen flex-col p-6">
        {children}
    </main>
        </body>
    </html>
  );
}
